import type { NativeBinding } from './api'
import type { TranspileOptions } from './types'
// The wasm loader is generated by `napi build --target wasm32-wasip1`
// (scripts/build-wasm.mjs) and ships in the @petrea/binding-wasm32-wasip1
// package next to the module it fetches. It instantiates the wasm module at
// import time — when that fails (no fetch, missing asset), the import of
// this entry rejects, and no partial exports are observable.
import * as wasip1Loader from '@petrea/binding-wasm32-wasip1'

import { createApi } from './api'

export type { OnError, TranspileOptions, UnsupportedSyntax } from './types'

function loadWasmBinding(): NativeBinding {
  return wasip1Loader as unknown as NativeBinding
}

const api = createApi(loadWasmBinding)

/**
 * Browser entry point: the same Rust pipeline compiled to WebAssembly
 * (`wasm32-wasip1`), loaded through `@napi-rs/wasm-runtime` from the
 * `@petrea/binding-wasm32-wasip1` package. The API mirrors the main entry
 * exactly.
 *
 * ```
 * import { transpile } from 'petrea/browser'
 *
 * await transpile(`const a: number = 1`)
 * // 'const a         = 1'
 * ```
 */
export const transpile: (input: string, options?: TranspileOptions) => Promise<string>
  = api.transpile

export const transpileSync: (input: string, options?: TranspileOptions) => string
  = api.transpileSync
