import type { NativeBinding } from './api'
import type { TranspileOptions } from './types'

// The wasm loader is generated by `napi build --target wasm32-wasip1`
// (scripts/build-wasm.mjs) and has no bundled type declarations; its shape
// matches NativeBinding.
// @ts-expect-error generated napi wasm loader ships without types
import * as wasip1Loader from '../wasm/oxc-blank-space-native.wasip1-browser.js'
import { createApi } from './api'

export type { OnError, TranspileOptions, UnsupportedSyntax } from './types'

function loadWasmBinding(): NativeBinding {
  return wasip1Loader as unknown as NativeBinding
}

const api = createApi(loadWasmBinding)

/**
 * Browser entry point: the same Rust pipeline compiled to WebAssembly
 * (`wasm32-wasip1`), loaded through `@napi-rs/wasm-runtime`. The API mirrors
 * the main entry exactly.
 *
 * ```
 * import { transpile } from '@teages/oxc-blank-space/browser'
 *
 * await transpile(`const a: number = 1`)
 * // 'const a         = 1'
 * ```
 */
export const transpile: (input: string, options?: TranspileOptions) => Promise<string>
  = api.transpile

export const transpileSync: (input: string, options?: TranspileOptions) => string
  = api.transpileSync

/**
 * Whether the wasm module loaded successfully. When false, {@link transpile}
 * and {@link transpileSync} throw on use.
 */
export const wasmBindingAvailable = api.isAvailable
